#ifndef WINDOWNAMEDEF_H_
#define WINDOWNAMEDEF_H_

//////////////////////////////////////////////////////////////////////////
// HMI Application Name
//////////////////////////////////////////////////////////////////////////

#define WIN_NAME_NONE                  ""

#define WIN_NAME_HOME                  "win_hmi_home"
#define WIN_NAME_SETTING               "win_hmi_settings"
#define WIN_NAME_HOME_SETTING          "win_hmi_home_setting"
#define WIN_NAME_HOME_EDIT_VIEW        "win_hmi_home_view"
#define WIN_NAME_RADIO                 "win_hmi_radio"
#define WIN_NAME_RADIO_SPEECHMODE      "win_hmi_radio_speechmode"
#define WIN_NAME_SXM360L               "win_hmi_sxm360l"
#define WIN_NAME_SXM360L_SPEECHMODE    "win_hmi_sxm360l_speechmode"
#define WIN_NAME_SXM360L_VOICESEARCH   "win_hmi_sxm360l_voicesearch"
#define WIN_NAME_MEDIA                 "win_hmi_media"
#define WIN_NAME_MEDIA_SPEECHMODE      "win_hmi_media_speechmode"
#define WIN_NAME_SIDE_PANEL_LEFT       "win_hmi_sidepanel_main"
#define WIN_NAME_SIDE_PANEL_RIGHT      "win_hmi_sidepanel_sub"
#define WIN_NAME_SIDE_PANEL_VIEW       "win_hmi_sidepanel_view"
#define WIN_NAME_SIDE_PANEL_VOLUME     "win_hmi_sidepanel_volume"
#define WIN_NAME_SIDE_STEPS            "win_hmi_sidesteps"
#define WIN_NAME_TOW_BAR               "win_hmi_towbar"
#define WIN_NAME_TOW_ASSIST            "win_hmi_towassist"
#define WIN_NAME_POPUP                 "win_hmi_popup"
#define WIN_NAME_PHONE                 "win_hmi_phone"
#define WIN_NAME_PHONE_OVERLAY         "win_hmi_phone_overlay"
#define WIN_NAME_PHONE_SPEECHMODE      "win_hmi_phone_speechmode"
#define WIN_NAME_ENG_SCR               "win_hmi_engscr"
#define WIN_NAME_ECO                   "win_hmi_eco"
#define WIN_NAME_SPEECH                "win_hmi_speech"
#define WIN_NAME_SPEECH_SPEECHMODE     "win_hmi_speech_speechmode"
#define WIN_NAME_VOICEPURE             "win_hmi_voicepure"
#define WIN_NAME_VOICEPURE_SPEECHMODE  "win_hmi_voicepure_speechmode"
#define WIN_NAME_SPEECHPTT             "win_hmi_speechptt"
#define WIN_NAME_CLIMATE               "win_hmi_climate"
#define WIN_NAME_CLIMATE_HARDKEY_BAR   "win_hmi_climate_hardkeybar"
#define WIN_NAME_SEAT                  "win_hmi_seat"
#define WIN_NAME_DYNAMICI              "win_hmi_dynamici"
#define WIN_NAME_LIGHTING              "win_hmi_lighting"
#define WIN_NAME_DRV4X4I               "win_hmi_drv4x4i"
#define WIN_NAME_DRV4X4I_HARDKEY_BAR   "win_hmi_drv4x4i_hardkeybar"
#define WIN_NAME_PHONE_PROJECTION      "win_hmi_phoneprojection"
#define WIN_NAME_LTL                   "win_hmi_ltl"
#define WIN_NAME_DIMENSION             "win_hmi_dimension"
#define WIN_NAME_ASI                   "win_hmi_asi"
#define WIN_NAME_LFL                   "win_hmi_lfl"
#define WIN_NAME_DEPICP                "win_hmi_depicp"
#define WIN_NAME_EV                    "win_hmi_ev"
#define WIN_NAME_SETTINGS              "win_hmi_settings"
#define WIN_NAME_SOURCESELECTOR        "win_hmi_sourceselector"
#define WIN_NAME_NAVI_HMI              "win_hmi_navi"
#define WIN_NAME_NAVI_HMI_SPEECHMODE   "win_hmi_navi_speechmode"
#define WIN_NAME_SOTA                  "win_hmi_sota"
#define WIN_NAME_PARKING               "win_hmi_parking"
#define WIN_NAME_SYSTEM_POPUP          "win_hmi_pop"
#define WIN_NAME_POPUP_ALERT           "win_alert_pop"
#define WIN_NAME_POPUP_EXCEPT          "win_except_pop"
#define WIN_NAME_POPUP_NORMAL          "win_normal_pop"
#define WIN_NAME_SYSTEM_KEYBOARD       "win_hmi_keyboard"
#define WIN_NAME_CAMERA                "win_hmi_camera"
#define WIN_NAME_CAMERA_LSMG           "win_hmi_camera_lsmg"
#define WIN_NAME_DCM                   "win_hmi_dcm"
#define WIN_NAME_DCR                   "win_hmi_dcr"
#define WIN_NAME_ONLINE_MEDIA          "win_hmi_onlinemedia"
#define WIN_NAME_ONLINEMEDIA_SPEECHMODE "win_hmi_onlinemedia_speechmode"
#define WIN_NAME_ONLINEMEDIA_ALEXAMODE "win_hmi_onlinemedia_alexamode"
#define WIN_NAME_ONLINEMEDIA_TMALLMODE "win_hmi_onlinemedia_tmallmode"
#define WIN_NAME_VALET_MODE            "win_hmi_valetmode"
#define WIN_NAME_NOTIFICATION          "win_hmi_notification"
#define WIN_NAME_SMART_SETTINGS        "win_hmi_smartsettings"
#define WIN_NAME_DISCLAIMER            "win_hmi_disclaimer"
#define WIN_NAME_DEPARTURE             "win_hmi_departure"
#define WIN_NAME_TJP                   "win_hmi_tjp"
#define WIN_NAME_GREETINGS             "win_hmi_greetings"
#define WIN_NAME_STARTUP_WIZARD        "win_hmi_startupwizard"
#define WIN_NAME_ACCOUNT               "win_hmi_account"
#define WIN_NAME_ACCOUNT_OVERLAY       "win_hmi_account_overlay"
#define WIN_NAME_SUPERICP              "lower_hmi_supericp"
#define WIN_NAME_LOWERSCREENBLADE      "lower_hmi_lowerscreenblade"

#define WIN_NAME_NAVI_MAP              "qnx_map_screen"
#define WIN_NAME_CAMERA_LAYER          "qnx_camera_screen"
#define WIN_NAME_SPLASH                "ssplash"
#define WIN_NAME_CCFSETTING            "win_hmi_ccfsetting"
#define WIN_NAME_CONNECTED_MSG         "win_hmi_connectedmsg"
#define WIN_NAME_SOURCEPICKER          "win_hmi_sourcepicker"
#define WIN_NAME_LOADING_WEBAPP        "win_hmi_loadingwebapp"
#define WIN_NAME_VEHICLECONTROLS       "win_hmi_vehiclecontrols"
#define WIN_NAME_VEHICLECONTROLS_DOOR  "win_hmi_vehiclecontrols_door_hardkeybar"
#define WIN_NAME_VEHICLECONTROLS_SUSPENSION  "win_hmi_vehiclecontrols_suspension_hardkeybar"
#define WIN_NAME_TEE		       "win_hmi_tee"
#define WIN_NAME_SEAT_VIEW_CONTROL     "win_hmi_seat_view_control_hardkeybar"
#define WIN_NAME_ALEXA                 "win_hmi_alexa"
#define WIN_NAME_ALEXA_VOICE_CHROME    "win_hmi_alexa_voice_chrome"
#define WIN_NAME_ALEXA_VISUAL_FEEDBACK "win_hmi_alexa_visual_feedback"
#define WIN_NAME_SHOWROOM              "win_hmi_showroom"
#define WIN_NAME_SHOWROOM_SERVICE      "win_showroom_service"
#define WIN_NAME_SHOWROOM_TOUCH        "win_showroom_touch"
#define WIN_NAME_TRANSPORT_HARDKEY_BAR "win_hmi_transport_hardkeybar"
#define WIN_NAME_TMALL                 "win_hmi_tmall"
#define WIN_NAME_TMALL_VOICE_CHROME    "win_hmi_tmall_voice_chrome"
#define WIN_NAME_TMALL_VISUAL_FEEDBACK "win_hmi_tmall_visual_feedback"
#define WIN_NAME_COMMON_BACKGROUND     "win_hmi_common_background"
#define WIN_NAME_COMMON_CALL_BUBBLE    "win_hmi_common_call_bubble"
#define WIN_HMI_COMMON_3D              "win_hmi_common_3d"

#define WIN_NAME_TEST1                 "win_hmi_test1"
#define WIN_NAME_TEST2                 "win_hmi_test2"
#define WIN_NAME_TEST3                 "win_hmi_test3"
#define WIN_NAME_TEST4                 "win_hmi_test4"
#define WIN_NAME_TEST5                 "win_hmi_test5"

#endif //WINDOWNAMEDEF_H_
