#ifndef BASEAPPMSGDEF_H
#define BASEAPPMSGDEF_H

#define INTERFACE_APP_VERSION "1.0"
#define INTERFACE_APP_SERVICE_OBJECT "/object/app/service"
#define INTERFACE_APP_PROXY_OBJECT "/object/app/proxy"

enum E_APP_SERVICE_MSG{
    E_APP_SERVICE_MSG_REQUESTTOREGISTERAPPLICATION1 = 1,
    E_APP_SERVICE_MSG_REQUESTTOREGISTERAPPLICATIONLINK1,
    E_APP_SERVICE_MSG_REQUESTTOGOBACK1,
    E_APP_SERVICE_MSG_REQUESTTOGOAPPLICATION_DEPRECATED_1,       // Deprecated : (requestID, eAppID, eViewID, eShowOpt, strIntent)
    E_APP_SERVICE_MSG_REQUESTTOGOAPPLICATION_DEPRECATED_2,       // Deprecated
    E_APP_SERVICE_MSG_REQUESTTOGOAPPLICATION_DEPRECATED_3,       // Deprecated
    E_APP_SERVICE_MSG_REQUESTTOGOAPPLICATION_DEPRECATED_4,       // Deprecated
    E_APP_SERVICE_MSG_REQUESTTOGOAPPLICATION1,
    E_APP_SERVICE_MSG_REQUESTTOGOAPPLICATION2,
    E_APP_SERVICE_MSG_REQUESTTOHIDEAPPLICATION_DEPRECATED_1,     // Deprecated
    E_APP_SERVICE_MSG_REQUESTTOHIDEAPPLICATION1,
    E_APP_SERVICE_MSG_REQUESTTOACTIVATEAPPLICATION_DEPRECATED_1, // Deprecated
    E_APP_SERVICE_MSG_REQUESTTOACTIVATEAPPLICATION1,
    E_APP_SERVICE_MSG_REQUESTTOSHOWSYSTEMCOMPONENT1,
    E_APP_SERVICE_MSG_REQUESTTOHIDESYSTEMCOMPONENT2,
    E_APP_SERVICE_MSG_REQUESTTOSETVISIBILITYOFSCREEN1,
    E_APP_SERVICE_MSG_REQUESTACTIVATEAUDIO1,
    E_APP_SERVICE_MSG_REQUESTUPDATEDYNAMICWINDOW1,
    E_APP_SERVICE_MSG_REQUESTTOSHOWPOPUP_DEPRECATED_1,           // Deprecated
    E_APP_SERVICE_MSG_REQUESTTOHIDEPOPUP_DEPRECATED_1,           // Deprecated
    E_APP_SERVICE_MSG_REQUESTTOSHOWKEYBOARD_DEPRECATED_1,        // Deprecated
    E_APP_SERVICE_MSG_REQUESTTOHIDEKEYBOARD_DEPRECATED_1,        // Deprecated
    E_APP_SERVICE_MSG_ONPOPUPACTIONRESULT_DEPRECATED_1,          // Deprecated
    E_APP_SERVICE_MSG_REQUESTTOSWITCHENTERTAINMENTAUDIO1,
    E_APP_SERVICE_MSG_REQUESTTOPLAYBEEPSOUND1,
    E_APP_SERVICE_MSG_REQUESTTOGETAVAILABLESCREEN1,
    E_APP_SERVICE_MSG_RESPONSEACTIVATEAPPLICATIONRESULT1,
    E_APP_SERVICE_MSG_RESPONSEGETAPPLICATIONACTIVATIONRESULT1,
    E_APP_SERVICE_MSG_RESPONSESHOWPOPUPRESULT_DEPRECATED_1,      // Deprecated
    E_APP_SERVICE_MSG_RESPONSEHIDEPOPUPRESULT_DEPRECATED_1,      // Deprecated
    E_APP_SERVICE_MSG_RESPONSESHOWKEYBOARDRESULT_DEPRECATED_1,   // Deprecated
    E_APP_SERVICE_MSG_RESPONSEHIDEKEYBOARDRESULT_DEPRECATED_1,   // Deprecated
    E_APP_SERVICE_MSG_RESPONSESHOWAPPLICATIONRESULT1,
    E_APP_SERVICE_MSG_RESPONSEHIDEAPPLICATIONRESULT1,
    E_APP_SERVICE_MSG_RESPONSERESUMEAPPLICATIONRESULT1,
    E_APP_SERVICE_MSG_RESPONSETERMINATEAPPLICATIONRESULT1,
    E_APP_SERVICE_MSG_RESPONSEREADYTOSUSPENDSYSTEMRESULT1,
    E_APP_SERVICE_MSG_RESPONSESUSPENDSYSTEMRESULT1,
    E_APP_SERVICE_MSG_RESPONSEREADYTORESUMESYSTEMRESULT1,
    E_APP_SERVICE_MSG_RESPONSERESUMESYSTEMRESULT1,
    E_APP_SERVICE_MSG_RESPONSEGOBACKRESULT1,
    E_APP_SERVICE_MSG_RESPONSESETVISIBILITYOFBACKBUTTONRESULT1,
    E_APP_SERVICE_MSG_REQUESTACTIVATEENTERTAINMENT1,
    E_APP_SERVICE_MSG_RESPONSECREATEAPPWINDOWRESULT1,
    E_APP_SERVICE_MSG_RESPONSESHOWAPPWINDOWRESULT1,
    E_APP_SERVICE_MSG_RESPONSEDESTROYAPPWINDOWRESULT1,
    E_APP_SERVICE_MSG_REQUESTCHANGESIDEPANELPOSITION1,
    E_APP_SERVICE_MSG_REQUESTTOUNREGISTERAPPLICATION1,
    E_APP_SERVICE_MSG_REQUESTTOHIDEAPPLICATION2,
    E_APP_SERVICE_MSG_REQUESTPOSTMESSAGE1,
    E_APP_SERVICE_MSG_REQUESTTOHIDEAPPLICATION3,
    E_APP_SERVICE_MSG_REQUESTCONTROLGUICOMPONENT1,
    E_APP_SERVICE_MSG_RESPONSECONTROLGUICOMPONENTRESULT1,
    E_APP_SERVICE_MSG_RESPONSESHOWTRANSITIONANIMATIONRESULT1,
    E_APP_SERVICE_MSG_RESPONSESETVISIBILITYOFHOMEBUTTONRESULT1,
    E_APP_SERVICE_MSG_REQUEST_NAVI_TYPE1,
    E_APP_SERVICE_MSG_REQUESTTODESTROYAPPWINDOW1,
    E_APP_SERVICE_MSG_REQUESTTOCOMMUNICATEAPPLICATION1,

    E_APP_SERVICE_MSG_REQUESTSTARTLOGGING1,
    E_APP_SERVICE_MSG_REQUESTSTOPLOGGING1,
    E_APP_SERVICE_MSG_REQUESTSETMEMORYSTRATEGY1,
};

enum E_APP_SERVICE_SYNC_MSG{
};

enum E_APP_LISTENER_MSG{
    E_APP_LISTENER_MSG_ONREGISTERAPPLICATIONRESULT1 = 1,
    E_APP_LISTENER_MSG_ONGOBACKRESULT1,
    E_APP_LISTENER_MSG_ONGOAPPLICATIONRESULT1,
    E_APP_LISTENER_MSG_ONHIDEAPPLICATIONRESULT1,
    E_APP_LISTENER_MSG_ONACTIVATEAPPLICATIONRESULT1,
    E_APP_LISTENER_MSG_ONSHOWSYSTEMCOMPONENTRESULT1,
    E_APP_LISTENER_MSG_ONHIDESYSTEMCOMPONENTRESULT1,
    E_APP_LISTENER_MSG_ONSETVISIBILITYOFSCREENRESULT1,
    E_APP_LISTENER_MSG_ONSHOWPOPUPRESULT1, // Deprecated
    E_APP_LISTENER_MSG_ONHIDEPOPUPRESULT1, // Deprecated
    E_APP_LISTENER_MSG_ONSHOWKEYBOARDRESULT1, // Deprecated
    E_APP_LISTENER_MSG_ONHIDEKEYBOARDRESULT1, // Deprecated
    E_APP_LISTENER_MSG_ONSWITCHENTERTAINMENTAUDIORESULT1, // Deprecated
    E_APP_LISTENER_MSG_ONPLAYBEEPSOUNDRESULT1,
    E_APP_LISTENER_MSG_ONGETAVAILABLESCREENRESULT1,
    E_APP_LISTENER_MSG_ONACTIVATEAUDIORESULT1,
    E_APP_LISTENER_MSG_ONUPDATEDYNAMICWINDOWRESULT1,
    E_APP_LISTENER_MSG_ONCMDACTIVATEAPPLICATION1,
    E_APP_LISTENER_MSG_ONCMDGETAPPLICATIONACTIVATION1,
    E_APP_LISTENER_MSG_ONCMDSHOWPOPUP1,
    E_APP_LISTENER_MSG_ONCMDHIDEPOPUP1,
    E_APP_LISTENER_MSG_ONCMDSHOWKEYBOARD1,
    E_APP_LISTENER_MSG_ONCMDHIDEKEYBOARD1,
    E_APP_LISTENER_MSG_ONCMDSHOWAPPLICATION1,
    E_APP_LISTENER_MSG_ONCMDSHOWAPPLICATION2,
    E_APP_LISTENER_MSG_ONCMDSHOWAPPLICATION3,
    E_APP_LISTENER_MSG_ONCMDSHOWAPPLICATION4,
    E_APP_LISTENER_MSG_ONCMDSHOWAPPLICATION5,
    E_APP_LISTENER_MSG_ONCMDHIDEAPPLICATION1,
    E_APP_LISTENER_MSG_ONCMDHIDEAPPLICATION2,
    E_APP_LISTENER_MSG_ONCMDRESUMEAPPLICATION1,
    E_APP_LISTENER_MSG_ONCMDRESUMEAPPLICATION2,
    E_APP_LISTENER_MSG_ONCMDRESUMEAPPLICATION3,
    E_APP_LISTENER_MSG_ONCMDCREATEAPPWINDOW1,
    E_APP_LISTENER_MSG_ONCMDSHOWAPPWINDOW1,
    E_APP_LISTENER_MSG_ONCMDDESTROYAPPWINDOW1,
    E_APP_LISTENER_MSG_ONCMDTERMINATEAPPLICATION1,
    E_APP_LISTENER_MSG_ONCMDGOBACK1,
    E_APP_LISTENER_MSG_ONCMDREADYTOSUSPENDSYSTEM1,
    E_APP_LISTENER_MSG_ONCMDSUSPENDSYSTEM1,
    E_APP_LISTENER_MSG_ONCMDREADYTORESUMESYSTEM1,
    E_APP_LISTENER_MSG_ONCMDRESUMESYSTEM1,
    E_APP_LISTENER_MSG_ONCMDSETVISIBILITYOFBACKBUTTON1,
    E_APP_LISTENER_MSG_ONBUTTONEVENT1,
    E_APP_LISTENER_MSG_ONROTARYEVENT1,
    E_APP_LISTENER_MSG_ONPOPUPACTIONRESULT1,
    E_APP_LISTENER_MSG_ONHMIAPPLICATIONFOREGROUNDSTATECHANGED1,
    E_APP_LISTENER_MSG_ONSYSTEMPOPUPVISIBILITYCHANGED1,
    E_APP_LISTENER_MSG_ONSYSTEMVALETMODESTATUSCHANGED1,
    E_APP_LISTENER_MSG_ONSYSTEMLANGUAGECHANGED1,
    E_APP_LISTENER_MSG_ONHMIAPPLICATIONFOREGROUNDSTATECHANGED2,
    E_APP_LISTENER_MSG_ONACTIVATEENTERTAINMENTRESULT1,
    E_APP_LISTENER_MSG_ONCHANGESIDEPANELPOSITIONRESULT1,
    E_APP_LISTENER_MSG_ONUNREGISTERAPPLICATIONRESULT1,
    E_APP_LISTENER_MSG_ONSHOWSYSTEMCOMPONENTRESULT2,
    E_APP_LISTENER_MSG_ONHIDESYSTEMCOMPONENTRESULT2,
    E_APP_LISTENER_MSG_ONPOSTMESSAGE1,
    E_APP_LISTENER_MSG_ONFAVOURITEBUTTONEVENT1,
    E_APP_LISTENER_MSG_ONCONTROLGUICOMPONENTRESULT1,
    E_APP_LISTENER_MSG_ONCMDCONTROLGUICOMPONENT1,
    E_APP_LISTENER_MSG_ONNOTIFYCLIENTCONNECTED1,
    E_APP_LISTENER_MSG_ONNOTIFYCLIENTDISCONNECTED1,
    E_APP_LISTENER_MSG_ONCMDSHOWTRANSITIONANIMATION1,
    E_APP_LISTENER_MSG_ONCMDSETVISIBILITYOFHOMEBUTTON1,
    E_APP_LISTENER_MSG_ONNOTIFYAPPLICATIONSTATUS1,
    E_APP_LISTENER_MSG_ONCOMMUNICATEAPPLICATIONEVENT1,
    E_APP_LISTENER_MSG_ONSHOWGOODBYESCREEN1,

    E_APP_LISTENER_MSG_ONBRFOREGROUNDAPPCHANGED1,
    E_APP_LISTENER_MSG_ONBRAPPSTACKCHANGED1,
    E_APP_LISTENER_MSG_ONBRAPPGRAPHCHANGED1,
    E_APP_LISTENER_MSG_ONBRMEMORYUSAGECHANGED1,
    E_APP_LISTENER_MSG_ONBRWINDOWLIFECHANGED1,
    E_APP_LISTENER_MSG_ONBRTOTALKPICHANGED1,
    E_APP_LISTENER_MSG_ONBRDESTROYTRIGGERED1,
    E_APP_LISTENER_MSG_ONBRMEMORYLEVELCHANGED1,
};

#endif //BASEAPPMSGDEF_H
